// Public DSL — builders
export { section, themeBlock } from './builders/section.js';
export { block } from './builders/block.js';
export {
  article,
  article_list,
  blog,
  checkbox,
  collection,
  collection_list,
  color,
  color_background,
  color_scheme,
  color_scheme_group,
  font_picker,
  header,
  html,
  image_picker,
  inline_richtext,
  link_list,
  liquid,
  metaobject,
  metaobject_list,
  number,
  page,
  paragraph,
  product,
  product_list,
  radio,
  range,
  richtext,
  select,
  text,
  text_alignment,
  textarea,
  url,
  video,
  video_url,
} from './builders/settings.js';

// Types — exposed for tooling and downstream packages
export type {
  AppBlockReference,
  ArticleListSetting,
  ArticleSetting,
  BlockDefinition,
  BlockPreset,
  BlogSetting,
  CheckboxSetting,
  CollectionListSetting,
  CollectionSetting,
  ColorBackgroundSetting,
  ColorSchemeGroupSetting,
  ColorSchemeSetting,
  ColorSetting,
  FontPickerSetting,
  HeaderSetting,
  HtmlSetting,
  ImagePickerSetting,
  InlineRichtextSetting,
  InputSetting,
  LinkListSetting,
  LiquidSetting,
  LocalBlockDefinition,
  LocaleString,
  MetaobjectListSetting,
  MetaobjectSetting,
  NamedBlockReference,
  NumberSetting,
  PageSetting,
  ParagraphSetting,
  ProductListSetting,
  ProductSetting,
  RadioSetting,
  RangeSetting,
  RichtextSetting,
  SectionDefinition,
  SectionEnabledOn,
  SectionPreset,
  SelectOption,
  SelectSetting,
  Setting,
  TextAlignmentSetting,
  TextSetting,
  TextareaSetting,
  ThemeBlockDefinition,
  ThemeBlockReference,
  UrlSetting,
  VideoSetting,
  VideoUrlSetting,
} from './types.js';

// Compile API — import directly from leaf modules (not the `compile/index.ts`
// re-export hub) so the bundled `.d.mts` emits clean named exports.
export { compileSection, compileThemeBlock, stringifySchema } from './compile/compile.js';
export type { SchemaJson } from './compile/compile.js';
export { findSchemaSpan, inlineSchema } from './compile/inline.js';
export type { InlineOptions } from './compile/inline.js';
export { formatIssue, hasErrors, validateSection, validateThemeBlock } from './compile/validate.js';
export type { ValidationIssue } from './compile/validate.js';
